pub struct AIR {}
pub struct STONE {}
pub struct GRANITE {}
pub struct POLISHED_GRANITE {}
pub struct DIORITE {}
pub struct POLISHED_DIORITE {}
pub struct ANDESITE {}
pub struct POLISHED_ANDESITE {}
pub struct GRASS_BLOCK {}
pub struct DIRT {}
pub struct COARSE_DIRT {}
pub struct PODZOL {}
pub struct COBBLESTONE {}
pub struct OAK_PLANKS {}
pub struct SPRUCE_PLANKS {}
pub struct BIRCH_PLANKS {}
pub struct JUNGLE_PLANKS {}
pub struct ACACIA_PLANKS {}
pub struct DARK_OAK_PLANKS {}
pub struct OAK_SAPLING {}
pub struct SPRUCE_SAPLING {}
pub struct BIRCH_SAPLING {}
pub struct JUNGLE_SAPLING {}
pub struct DARK_OAK_SAPLING {}
pub struct BEDROCK {}
pub struct WATER {}
pub struct LAVA {}
pub struct SAND {}
pub struct RED_SAND {}
pub struct GRAVEL {}
pub struct GOLD_ORE {}
pub struct DEEPSLATE_GOLD_ORE {}
pub struct IRON_ORE {}
pub struct DEEPSLATE_IRON_ORE {}
pub struct COAL_ORE {}
pub struct DEEPSLATE_COAL_ORE {}
pub struct NETHER_GOLD_ORE {}
pub struct OAK_LOG {}
pub struct SPRUCE_LOG {}
pub struct BIRCH_LOG {}
pub struct JUNGLE_LOG {}
pub struct ACACIA_LOG {}
pub struct DARK_OAK_LOG {}
pub struct STRIPPED_SPRUCE_LOG {}
pub struct STRIPPED_BIRCH_LOG {}
pub struct STRIPPED_JUNGLE_LOG {}
pub struct STRIPPED_ACACIA_LOG {}
pub struct STRIPPED_DARK_OAK_LOG {}
pub struct STRIPPED_OAK_LOG {}
pub struct OAK_WOOD {}
pub struct SPRUCE_WOOD {}
pub struct BIRCH_WOOD {}
pub struct JUNGLE_WOOD {}
pub struct ACACIA_WOOD {}
pub struct DARK_OAK_WOOD {}
pub struct STRIPPED_OAK_WOOD {}
pub struct STRIPPED_SPRUCE_WOOD {}
pub struct STRIPPED_BIRCH_WOOD {}
pub struct STRIPPED_JUNGLE_WOOD {}
pub struct STRIPPED_ACACIA_WOOD {}
pub struct STRIPPED_DARK_OAK_WOOD {}
pub struct OAK_LEAVES {}
pub struct SPRUCE_LEAVES {}
pub struct BIRCH_LEAVES {}
pub struct JUNGLE_LEAVES {}
pub struct ACACIA_LEAVES {}
pub struct DARK_OAK_LEAVES {}
pub struct AZALEA_LEAVES {}
pub struct FLOWERING_AZALEA_LEAVES {}
pub struct SPONGE {}
pub struct WET_SPONGE {}
pub struct GLASS {}
pub struct LAPIS_ORE {}
pub struct DEEPSLATE_LAPIS_ORE {}
pub struct LAPIS_BLOCK {}
pub struct DISPENSER {}
pub struct SANDSTONE {}
pub struct CHISELED_SANDSTONE {}
pub struct CUT_SANDSTONE {}
pub struct NOTE_BLOCK {}
pub struct WHITE_BED {}
pub struct ORANGE_BED {}
pub struct MAGENTA_BED {}
pub struct LIGHT_BLUE_BED {}
pub struct YELLOW_BED {}
pub struct LIME_BED {}
pub struct PINK_BED {}
pub struct GRAY_BED {}
pub struct LIGHT_GRAY_BED {}
pub struct CYAN_BED {}
pub struct PURPLE_BED {}
pub struct BLUE_BED {}
pub struct BROWN_BED {}
pub struct GREEN_BED {}
pub struct RED_BED {}
pub struct BLACK_BED {}
pub struct POWERED_RAIL {}
pub struct DETECTOR_RAIL {}
pub struct STICKY_PISTON {}
pub struct COBWEB {}
pub struct GRASS {}
pub struct FERN {}
pub struct DEAD_BUSH {}
pub struct SEAGRASS {}
pub struct TALL_SEAGRASS {}
pub struct PISTON {}
pub struct PISTON_HEAD {}
pub struct WHITE_WOOL {}
pub struct ORANGE_WOOL {}
pub struct MAGENTA_WOOL {}
pub struct LIGHT_BLUE_WOOL {}
pub struct YELLOW_WOOL {}
pub struct LIME_WOOL {}
pub struct PINK_WOOL {}
pub struct GRAY_WOOL {}
pub struct LIGHT_GRAY_WOOL {}
pub struct CYAN_WOOL {}
pub struct PURPLE_WOOL {}
pub struct BLUE_WOOL {}
pub struct BROWN_WOOL {}
pub struct GREEN_WOOL {}
pub struct RED_WOOL {}
pub struct BLACK_WOOL {}
pub struct MOVING_PISTON {}
pub struct DANDELION {}
pub struct POPPY {}
pub struct BLUE_ORCHID {}
pub struct ALLIUM {}
pub struct AZURE_BLUET {}
pub struct RED_TULIP {}
pub struct ORANGE_TULIP {}
pub struct WHITE_TULIP {}
pub struct PINK_TULIP {}
pub struct OXEYE_DAISY {}
pub struct CORNFLOWER {}
pub struct WITHER_ROSE {}
pub struct LILY_OF_THE_VALLEY {}
pub struct BROWN_MUSHROOM {}
pub struct RED_MUSHROOM {}
pub struct GOLD_BLOCK {}
pub struct IRON_BLOCK {}
pub struct BRICKS {}
pub struct TNT {}
pub struct BOOKSHELF {}
pub struct MOSSY_COBBLESTONE {}
pub struct OBSIDIAN {}
pub struct TORCH {}
pub struct WALL_TORCH {}
pub struct FIRE {}
pub struct SOUL_FIRE {}
pub struct SPAWNER {}
pub struct OAK_STAIRS {}
pub struct CHEST {}
pub struct REDSTONE_WIRE {}
pub struct DIAMOND_ORE {}
pub struct DEEPSLATE_DIAMOND_ORE {}
pub struct DIAMOND_BLOCK {}
pub struct CRAFTING_TABLE {}
pub struct WHEAT {}
pub struct FARMLAND {}
pub struct FURNACE {}
pub struct OAK_SIGN {}
pub struct SPRUCE_SIGN {}
pub struct BIRCH_SIGN {}
pub struct ACACIA_SIGN {}
pub struct JUNGLE_SIGN {}
pub struct DARK_OAK_SIGN {}
pub struct OAK_DOOR {}
pub struct LADDER {}
pub struct RAIL {}
pub struct COBBLESTONE_STAIRS {}
pub struct OAK_WALL_SIGN {}
pub struct SPRUCE_WALL_SIGN {}
pub struct BIRCH_WALL_SIGN {}
pub struct ACACIA_WALL_SIGN {}
pub struct JUNGLE_WALL_SIGN {}
pub struct DARK_OAK_WALL_SIGN {}
pub struct LEVER {}
pub struct STONE_PRESSURE_PLATE {}
pub struct IRON_DOOR {}
pub struct OAK_PRESSURE_PLATE {}
pub struct SPRUCE_PRESSURE_PLATE {}
pub struct BIRCH_PRESSURE_PLATE {}
pub struct JUNGLE_PRESSURE_PLATE {}
pub struct ACACIA_PRESSURE_PLATE {}
pub struct DARK_OAK_PRESSURE_PLATE {}
pub struct REDSTONE_ORE {}
pub struct DEEPSLATE_REDSTONE_ORE {}
pub struct REDSTONE_TORCH {}
pub struct REDSTONE_WALL_TORCH {}
pub struct STONE_BUTTON {}
pub struct SNOW {}
pub struct ICE {}
pub struct SNOW_BLOCK {}
pub struct CACTUS {}
pub struct CLAY {}
pub struct SUGAR_CANE {}
pub struct JUKEBOX {}
pub struct OAK_FENCE {}
pub struct PUMPKIN {}
pub struct NETHERRACK {}
pub struct SOUL_SAND {}
pub struct SOUL_SOIL {}
pub struct BASALT {}
pub struct POLISHED_BASALT {}
pub struct SOUL_TORCH {}
pub struct SOUL_WALL_TORCH {}
pub struct GLOWSTONE {}
pub struct NETHER_PORTAL {}
pub struct CARVED_PUMPKIN {}
pub struct JACK_O_LANTERN {}
pub struct CAKE {}
pub struct REPEATER {}
pub struct WHITE_STAINED_GLASS {}
pub struct ORANGE_STAINED_GLASS {}
pub struct MAGENTA_STAINED_GLASS {}
pub struct LIGHT_BLUE_STAINED_GLASS {}
pub struct YELLOW_STAINED_GLASS {}
pub struct LIME_STAINED_GLASS {}
pub struct PINK_STAINED_GLASS {}
pub struct GRAY_STAINED_GLASS {}
pub struct LIGHT_GRAY_STAINED_GLASS {}
pub struct CYAN_STAINED_GLASS {}
pub struct PURPLE_STAINED_GLASS {}
pub struct BLUE_STAINED_GLASS {}
pub struct BROWN_STAINED_GLASS {}
pub struct GREEN_STAINED_GLASS {}
pub struct RED_STAINED_GLASS {}
pub struct BLACK_STAINED_GLASS {}
pub struct OAK_TRAPDOOR {}
pub struct SPRUCE_TRAPDOOR {}
pub struct BIRCH_TRAPDOOR {}
pub struct JUNGLE_TRAPDOOR {}
pub struct ACACIA_TRAPDOOR {}
pub struct DARK_OAK_TRAPDOOR {}
pub struct STONE_BRICKS {}
pub struct MOSSY_STONE_BRICKS {}
pub struct CRACKED_STONE_BRICKS {}
pub struct CHISELED_STONE_BRICKS {}
pub struct INFESTED_STONE {}
pub struct INFESTED_COBBLESTONE {}
pub struct INFESTED_STONE_BRICKS {}
pub struct INFESTED_MOSSY_STONE_BRICKS {}
pub struct INFESTED_CRACKED_STONE_BRICKS {}
pub struct INFESTED_CHISELED_STONE_BRICKS {}
pub struct BROWN_MUSHROOM_BLOCK {}
pub struct RED_MUSHROOM_BLOCK {}
pub struct MUSHROOM_STEM {}
pub struct IRON_BARS {}
pub struct CHAIN {}
pub struct GLASS_PANE {}
pub struct MELON {}
pub struct ATTACHED_PUMPKIN_STEM {}
pub struct ATTACHED_MELON_STEM {}
pub struct PUMPKIN_STEM {}
pub struct MELON_STEM {}
pub struct VINE {}
pub struct GLOW_LICHEN {}
pub struct OAK_FENCE_GATE {}
pub struct BRICK_STAIRS {}
pub struct STONE_BRICK_STAIRS {}
pub struct MYCELIUM {}
pub struct LILY_PAD {}
pub struct NETHER_BRICKS {}
pub struct NETHER_BRICK_FENCE {}
pub struct NETHER_BRICK_STAIRS {}
pub struct NETHER_WART {}
pub struct ENCHANTING_TABLE {}
pub struct BREWING_STAND {}
pub struct CAULDRON {}
pub struct WATER_CAULDRON {}
pub struct LAVA_CAULDRON {}
pub struct POWDER_SNOW_CAULDRON {}
pub struct END_PORTAL {}
pub struct END_PORTAL_FRAME {}
pub struct END_STONE {}
pub struct DRAGON_EGG {}
pub struct REDSTONE_LAMP {}
pub struct COCOA {}
pub struct SANDSTONE_STAIRS {}
pub struct EMERALD_ORE {}
pub struct DEEPSLATE_EMERALD_ORE {}
pub struct ENDER_CHEST {}
pub struct TRIPWIRE_HOOK {}
pub struct TRIPWIRE {}
pub struct EMERALD_BLOCK {}
pub struct SPRUCE_STAIRS {}
pub struct BIRCH_STAIRS {}
pub struct JUNGLE_STAIRS {}
pub struct COMMAND_BLOCK {}
pub struct BEACON {}
pub struct COBBLESTONE_WALL {}
pub struct MOSSY_COBBLESTONE_WALL {}
pub struct FLOWER_POT {}
pub struct POTTED_OAK_SAPLING {}
pub struct POTTED_SPRUCE_SAPLING {}
pub struct POTTED_BIRCH_SAPLING {}
pub struct POTTED_JUNGLE_SAPLING {}
pub struct POTTED_ACACIA_SAPLING {}
pub struct POTTED_DARK_OAK_SAPLING {}
pub struct POTTED_FERN {}
pub struct POTTED_DANDELION {}
pub struct POTTED_POPPY {}
pub struct POTTED_BLUE_ORCHID {}
pub struct POTTED_ALLIUM {}
pub struct POTTED_AZURE_BLUET {}
pub struct POTTED_RED_TULIP {}
pub struct POTTED_ORANGE_TULIP {}
pub struct POTTED_WHITE_TULIP {}
pub struct POTTED_PINK_TULIP {}
pub struct POTTED_OXEYE_DAISY {}
pub struct POTTED_CORNFLOWER {}
pub struct POTTED_LILY_OF_THE_VALLEY {}
pub struct POTTED_WITHER_ROSE {}
pub struct POTTED_RED_MUSHROOM {}
pub struct POTTED_BROWN_MUSHROOM {}
pub struct POTTED_DEAD_BUSH {}
pub struct POTTED_CACTUS {}
pub struct CARROTS {}
pub struct POTATOES {}
pub struct OAK_BUTTON {}
pub struct SPRUCE_BUTTON {}
pub struct BIRCH_BUTTON {}
pub struct JUNGLE_BUTTON {}
pub struct ACACIA_BUTTON {}
pub struct DARK_OAK_BUTTON {}
pub struct SKELETON_SKULL {}
pub struct SKELETON_WALL_SKULL {}
pub struct WITHER_SKELETON_SKULL {}
pub struct WITHER_SKELETON_WALL_SKULL {}
pub struct ZOMBIE_HEAD {}
pub struct ZOMBIE_WALL_HEAD {}
pub struct PLAYER_HEAD {}
pub struct PLAYER_WALL_HEAD {}
pub struct CREEPER_HEAD {}
pub struct CREEPER_WALL_HEAD {}
pub struct DRAGON_HEAD {}
pub struct DRAGON_WALL_HEAD {}
pub struct ANVIL {}
pub struct CHIPPED_ANVIL {}
pub struct DAMAGED_ANVIL {}
pub struct TRAPPED_CHEST {}
pub struct LIGHT_WEIGHTED_PRESSURE_PLATE {}
pub struct HEAVY_WEIGHTED_PRESSURE_PLATE {}
pub struct COMPARATOR {}
pub struct DAYLIGHT_DETECTOR {}
pub struct REDSTONE_BLOCK {}
pub struct NETHER_QUARTZ_ORE {}
pub struct HOPPER {}
pub struct QUARTZ_BLOCK {}
pub struct CHISELED_QUARTZ_BLOCK {}
pub struct QUARTZ_PILLAR {}
pub struct QUARTZ_STAIRS {}
pub struct ACTIVATOR_RAIL {}
pub struct DROPPER {}
pub struct WHITE_TERRACOTTA {}
pub struct ORANGE_TERRACOTTA {}
pub struct MAGENTA_TERRACOTTA {}
pub struct LIGHT_BLUE_TERRACOTTA {}
pub struct YELLOW_TERRACOTTA {}
pub struct LIME_TERRACOTTA {}
pub struct PINK_TERRACOTTA {}
pub struct GRAY_TERRACOTTA {}
pub struct LIGHT_GRAY_TERRACOTTA {}
pub struct CYAN_TERRACOTTA {}
pub struct PURPLE_TERRACOTTA {}
pub struct BLUE_TERRACOTTA {}
pub struct BROWN_TERRACOTTA {}
pub struct GREEN_TERRACOTTA {}
pub struct RED_TERRACOTTA {}
pub struct BLACK_TERRACOTTA {}
pub struct WHITE_STAINED_GLASS_PANE {}
pub struct ORANGE_STAINED_GLASS_PANE {}
pub struct MAGENTA_STAINED_GLASS_PANE {}
pub struct LIGHT_BLUE_STAINED_GLASS_PANE {}
pub struct YELLOW_STAINED_GLASS_PANE {}
pub struct LIME_STAINED_GLASS_PANE {}
pub struct PINK_STAINED_GLASS_PANE {}
pub struct GRAY_STAINED_GLASS_PANE {}
pub struct LIGHT_GRAY_STAINED_GLASS_PANE {}
pub struct CYAN_STAINED_GLASS_PANE {}
pub struct PURPLE_STAINED_GLASS_PANE {}
pub struct BLUE_STAINED_GLASS_PANE {}
pub struct BROWN_STAINED_GLASS_PANE {}
pub struct GREEN_STAINED_GLASS_PANE {}
pub struct RED_STAINED_GLASS_PANE {}
pub struct BLACK_STAINED_GLASS_PANE {}
pub struct ACACIA_STAIRS {}
pub struct DARK_OAK_STAIRS {}
pub struct SLIME_BLOCK {}
pub struct BARRIER {}
pub struct LIGHT {}
pub struct IRON_TRAPDOOR {}
pub struct PRISMARINE {}
pub struct PRISMARINE_BRICKS {}
pub struct DARK_PRISMARINE {}
pub struct PRISMARINE_STAIRS {}
pub struct PRISMARINE_BRICK_STAIRS {}
pub struct DARK_PRISMARINE_STAIRS {}
pub struct PRISMARINE_SLAB {}
pub struct PRISMARINE_BRICK_SLAB {}
pub struct DARK_PRISMARINE_SLAB {}
pub struct SEA_LANTERN {}
pub struct HAY_BLOCK {}
pub struct WHITE_CARPET {}
pub struct ORANGE_CARPET {}
pub struct MAGENTA_CARPET {}
pub struct LIGHT_BLUE_CARPET {}
pub struct YELLOW_CARPET {}
pub struct LIME_CARPET {}
pub struct PINK_CARPET {}
pub struct GRAY_CARPET {}
pub struct LIGHT_GRAY_CARPET {}
pub struct CYAN_CARPET {}
pub struct PURPLE_CARPET {}
pub struct BLUE_CARPET {}
pub struct BROWN_CARPET {}
pub struct GREEN_CARPET {}
pub struct RED_CARPET {}
pub struct BLACK_CARPET {}
pub struct TERRACOTTA {}
pub struct COAL_BLOCK {}
pub struct PACKED_ICE {}
pub struct SUNFLOWER {}
pub struct LILAC {}
pub struct ROSE_BUSH {}
pub struct PEONY {}
pub struct TALL_GRASS {}
pub struct LARGE_FERN {}
pub struct WHITE_BANNER {}
pub struct ORANGE_BANNER {}
pub struct MAGENTA_BANNER {}
pub struct LIGHT_BLUE_BANNER {}
pub struct YELLOW_BANNER {}
pub struct LIME_BANNER {}
pub struct PINK_BANNER {}
pub struct GRAY_BANNER {}
pub struct LIGHT_GRAY_BANNER {}
pub struct CYAN_BANNER {}
pub struct PURPLE_BANNER {}
pub struct BLUE_BANNER {}
pub struct BROWN_BANNER {}
pub struct GREEN_BANNER {}
pub struct RED_BANNER {}
pub struct BLACK_BANNER {}
pub struct WHITE_WALL_BANNER {}
pub struct ORANGE_WALL_BANNER {}
pub struct MAGENTA_WALL_BANNER {}
pub struct LIGHT_BLUE_WALL_BANNER {}
pub struct YELLOW_WALL_BANNER {}
pub struct LIME_WALL_BANNER {}
pub struct PINK_WALL_BANNER {}
pub struct GRAY_WALL_BANNER {}
pub struct LIGHT_GRAY_WALL_BANNER {}
pub struct CYAN_WALL_BANNER {}
pub struct PURPLE_WALL_BANNER {}
pub struct BLUE_WALL_BANNER {}
pub struct BROWN_WALL_BANNER {}
pub struct GREEN_WALL_BANNER {}
pub struct RED_WALL_BANNER {}
pub struct BLACK_WALL_BANNER {}
pub struct RED_SANDSTONE {}
pub struct CHISELED_RED_SANDSTONE {}
pub struct CUT_RED_SANDSTONE {}
pub struct RED_SANDSTONE_STAIRS {}
pub struct OAK_SLAB {}
pub struct SPRUCE_SLAB {}
pub struct BIRCH_SLAB {}
pub struct JUNGLE_SLAB {}
pub struct ACACIA_SLAB {}
pub struct DARK_OAK_SLAB {}
pub struct STONE_SLAB {}
pub struct SMOOTH_STONE_SLAB {}
pub struct SANDSTONE_SLAB {}
pub struct CUT_SANDSTONE_SLAB {}
pub struct PETRIFIED_OAK_SLAB {}
pub struct COBBLESTONE_SLAB {}
pub struct BRICK_SLAB {}
pub struct STONE_BRICK_SLAB {}
pub struct NETHER_BRICK_SLAB {}
pub struct QUARTZ_SLAB {}
pub struct RED_SANDSTONE_SLAB {}
pub struct CUT_RED_SANDSTONE_SLAB {}
pub struct PURPUR_SLAB {}
pub struct SMOOTH_STONE {}
pub struct SMOOTH_SANDSTONE {}
pub struct SMOOTH_QUARTZ {}
pub struct SMOOTH_RED_SANDSTONE {}
pub struct SPRUCE_FENCE_GATE {}
pub struct BIRCH_FENCE_GATE {}
pub struct JUNGLE_FENCE_GATE {}
pub struct ACACIA_FENCE_GATE {}
pub struct DARK_OAK_FENCE_GATE {}
pub struct SPRUCE_FENCE {}
pub struct BIRCH_FENCE {}
pub struct JUNGLE_FENCE {}
pub struct ACACIA_FENCE {}
pub struct DARK_OAK_FENCE {}
pub struct SPRUCE_DOOR {}
pub struct BIRCH_DOOR {}
pub struct JUNGLE_DOOR {}
pub struct ACACIA_DOOR {}
pub struct DARK_OAK_DOOR {}
pub struct END_ROD {}
pub struct CHORUS_PLANT {}
pub struct CHORUS_FLOWER {}
pub struct PURPUR_BLOCK {}
pub struct PURPUR_PILLAR {}
pub struct PURPUR_STAIRS {}
pub struct END_STONE_BRICKS {}
pub struct Beetroots {}
pub struct DirtPath {}
pub struct EndGateway {}
pub struct RepeatingCommandBlock {}
pub struct ChainCommandBlock {}
pub struct FrostedIce {}
pub struct MagmaBlock {}
pub struct NetherWartBlock {}
pub struct RedNetherBricks {}
pub struct BoneBlock {}
pub struct StructureVoid {}
pub struct Observer {}
pub struct ShulkerBox {}
pub struct WhiteShulkerBox {}
pub struct OrangeShulkerBox {}
pub struct MagentaShulkerBox {}
pub struct LightBlueShulkerBox {}
pub struct YellowShulkerBox {}
pub struct LimeShulkerBox {}
pub struct PinkShulkerBox {}
pub struct GrayShulkerBox {}
pub struct LightGrayShulkerBox {}
pub struct CyanShulkerBox {}
pub struct PurpleShulkerBox {}
pub struct BlueShulkerBox {}
pub struct BrownShulkerBox {}
pub struct GreenShulkerBox {}
pub struct RedShulkerBox {}
pub struct BlackShulkerBox {}
pub struct WhiteGlazedTerracotta {}
pub struct OrangeGlazedTerracotta {}
pub struct MagentaGlazedTerracotta {}
pub struct LightBlueGlazedTerracotta {}
pub struct YellowGlazedTerracotta {}
pub struct LimeGlazedTerracotta {}
pub struct PinkGlazedTerracotta {}
pub struct GrayGlazedTerracotta {}
pub struct LightGrayGlazedTerracotta {}
pub struct CyanGlazedTerracotta {}
pub struct PurpleGlazedTerracotta {}
pub struct BlueGlazedTerracotta {}
pub struct BrownGlazedTerracotta {}
pub struct GreenGlazedTerracotta {}
pub struct RedGlazedTerracotta {}
pub struct BlackGlazedTerracotta {}
pub struct WhiteConcrete {}
pub struct OrangeConcrete {}
pub struct MagentaConcrete {}
pub struct LightBlueConcrete {}
pub struct YellowConcrete {}
pub struct LimeConcrete {}
pub struct PinkConcrete {}
pub struct GrayConcrete {}
pub struct LightGrayConcrete {}
pub struct CyanConcrete {}
pub struct PurpleConcrete {}
pub struct BlueConcrete {}
pub struct BrownConcrete {}
pub struct GreenConcrete {}
pub struct RedConcrete {}
pub struct BlackConcrete {}
pub struct WhiteConcretePowder {}
pub struct OrangeConcretePowder {}
pub struct MagentaConcretePowder {}
pub struct LightBlueConcretePowder {}
pub struct YellowConcretePowder {}
pub struct LimeConcretePowder {}
pub struct PinkConcretePowder {}
pub struct GrayConcretePowder {}
pub struct LightGrayConcretePowder {}
pub struct CyanConcretePowder {}
pub struct PurpleConcretePowder {}
pub struct BlueConcretePowder {}
pub struct BrownConcretePowder {}
pub struct GreenConcretePowder {}
pub struct RedConcretePowder {}
pub struct BlackConcretePowder {}
pub struct KELP {}
pub struct KelpPlant {}
pub struct DriedKelpBlock {}
pub struct TurtleEgg {}
pub struct DeadTubeCoralBlock {}
pub struct DeadBrainCoralBlock {}
pub struct DeadBubbleCoralBlock {}
pub struct DeadFireCoralBlock {}
pub struct DeadHornCoralBlock {}
pub struct TubeCoralBlock {}
pub struct BrainCoralBlock {}
pub struct BubbleCoralBlock {}
pub struct FireCoralBlock {}
pub struct HornCoralBlock {}
pub struct DeadTubeCoral {}
pub struct DeadBrainCoral {}
pub struct DeadBubbleCoral {}
pub struct DeadFireCoral {}
pub struct DeadHornCoral {}
pub struct TubeCoral {}
pub struct BrainCoral {}
pub struct BubbleCoral {}
pub struct FireCoral {}
pub struct HornCoral {}
pub struct DeadTubeCoralFan {}
pub struct DeadBrainCoralFan {}
pub struct DeadBubbleCoralFan {}
pub struct DeadFireCoralFan {}
pub struct DeadHornCoralFan {}
pub struct TubeCoralFan {}
pub struct BrainCoralFan {}
pub struct BubbleCoralFan {}
pub struct FireCoralFan {}
pub struct HornCoralFan {}
pub struct DeadTubeCoralWallFan {}
pub struct DeadBrainCoralWallFan {}
pub struct DeadBubbleCoralWallFan {}
pub struct DeadFireCoralWallFan {}
pub struct DeadHornCoralWallFan {}
pub struct TubeCoralWallFan {}
pub struct BrainCoralWallFan {}
pub struct BubbleCoralWallFan {}
pub struct FireCoralWallFan {}
pub struct HornCoralWallFan {}
pub struct SeaPickle {}
pub struct BlueIce {}
pub struct Conduit {}
pub struct BambooSapling {}
pub struct Bamboo {}
pub struct PottedBamboo {}
pub struct VoidAir {}
pub struct CaveAir {}
pub struct BubbleColumn {}
pub struct PolishedGraniteStairs {}
pub struct SmoothRedSandstoneStairs {}
pub struct MossyStoneBrickStairs {}
pub struct PolishedDioriteStairs {}
pub struct MossyCobblestoneStairs {}
pub struct EndStoneBrickStairs {}
pub struct StoneStairs {}
pub struct SmoothSandstoneStairs {}
pub struct SmoothQuartzStairs {}
pub struct GraniteStairs {}
pub struct AndesiteStairs {}
pub struct RedNetherBrickStairs {}
pub struct PolishedAndesiteStairs {}
pub struct DioriteStairs {}
pub struct PolishedGraniteSlab {}
pub struct SmoothRedSandstoneSlab {}
pub struct MossyStoneBrickSlab {}
pub struct PolishedDioriteSlab {}
pub struct MossyCobblestoneSlab {}
pub struct EndStoneBrickSlab {}
pub struct SmoothSandstoneSlab {}
pub struct SmoothQuartzSlab {}
pub struct GraniteSlab {}
pub struct AndesiteSlab {}
pub struct RedNetherBrickSlab {}
pub struct PolishedAndesiteSlab {}
pub struct DioriteSlab {}
pub struct BrickWall {}
pub struct PrismarineWall {}
pub struct RedSandstoneWall {}
pub struct MossyStoneBrickWall {}
pub struct GraniteWall {}
pub struct StoneBrickWall {}
pub struct NetherBrickWall {}
pub struct AndesiteWall {}
pub struct RedNetherBrickWall {}
pub struct SandstoneWall {}
pub struct EndStoneBrickWall {}
pub struct DioriteWall {}
pub struct Scaffolding {}
pub struct Loom {}
pub struct Barrel {}
pub struct Smoker {}
pub struct BlastFurnace {}
pub struct CartographyTable {}
pub struct FletchingTable {}
pub struct Grindstone {}
pub struct Lectern {}
pub struct SmithingTable {}
pub struct Stonecutter {}
pub struct Bell {}
pub struct Lantern {}
pub struct SoulLantern {}
pub struct Campfire {}
pub struct SoulCampfire {}
pub struct SweetBerryBush {}
pub struct WarpedStem {}
pub struct StrippedWarpedStem {}
pub struct WarpedHyphae {}
pub struct StrippedWarpedHyphae {}
pub struct WarpedNylium {}
pub struct WarpedFungus {}
pub struct WarpedWartBlock {}
pub struct WarpedRoots {}
pub struct NetherSprouts {}
pub struct CrimsonStem {}
pub struct StrippedCrimsonStem {}
pub struct CrimsonHyphae {}
pub struct StrippedCrimsonHyphae {}
pub struct CrimsonNylium {}
pub struct CrimsonFungus {}
pub struct Shroomlight {}
pub struct WeepingVines {}
pub struct WeepingVinesPlant {}
pub struct TwistingVines {}
pub struct TwistingVinesPlant {}
pub struct CrimsonRoots {}
pub struct CrimsonPlanks {}
pub struct WarpedPlanks {}
pub struct CrimsonSlab {}
pub struct WarpedSlab {}
pub struct CrimsonPressurePlate {}
pub struct WarpedPressurePlate {}
pub struct CrimsonFence {}
pub struct WarpedFence {}
pub struct CrimsonTrapdoor {}
pub struct WarpedTrapdoor {}
pub struct CrimsonFenceGate {}
pub struct WarpedFenceGate {}
pub struct CrimsonStairs {}
pub struct WarpedStairs {}
pub struct CrimsonButton {}
pub struct WarpedButton {}
pub struct CrimsonDoor {}
pub struct WarpedDoor {}
pub struct CrimsonSign {}
pub struct WarpedSign {}
pub struct CrimsonWallSign {}
pub struct WarpedWallSign {}
pub struct StructureBlock {}
pub struct Jigsaw {}
pub struct Composter {}
pub struct Target {}
pub struct BeeNest {}
pub struct Beehive {}
pub struct HoneyBlock {}
pub struct HoneycombBlock {}
pub struct NetheriteBlock {}
pub struct AncientDebris {}
pub struct CryingObsidian {}
pub struct RespawnAnchor {}
pub struct PottedCrimsonFungus {}
pub struct PottedWarpedFungus {}
pub struct PottedCrimsonRoots {}
pub struct PottedWarpedRoots {}
pub struct Lodestone {}
pub struct Blackstone {}
pub struct BlackstoneStairs {}
pub struct BlackstoneWall {}
pub struct BlackstoneSlab {}
pub struct PolishedBlackstone {}
pub struct PolishedBlackstoneBricks {}
pub struct CrackedPolishedBlackstoneBricks {}
pub struct ChiseledPolishedBlackstone {}
pub struct PolishedBlackstoneBrickSlab {}
pub struct PolishedBlackstoneBrickStairs {}
pub struct PolishedBlackstoneBrickWall {}
pub struct GildedBlackstone {}
pub struct PolishedBlackstoneStairs {}
pub struct PolishedBlackstoneSlab {}
pub struct PolishedBlackstonePressurePlate {}
pub struct PolishedBlackstoneButton {}
pub struct PolishedBlackstoneWall {}
pub struct ChiseledNetherBricks {}
pub struct CrackedNetherBricks {}
pub struct QuartzBricks {}
pub struct Candle {}
pub struct WhiteCandle {}
pub struct OrangeCandle {}
pub struct MagentaCandle {}
pub struct LightBlueCandle {}
pub struct YellowCandle {}
pub struct LimeCandle {}
pub struct PinkCandle {}
pub struct GrayCandle {}
pub struct LightGrayCandle {}
pub struct CyanCandle {}
pub struct PurpleCandle {}
pub struct BlueCandle {}
pub struct BrownCandle {}
pub struct GreenCandle {}
pub struct RedCandle {}
pub struct BlackCandle {}
pub struct CandleCake {}
pub struct WhiteCandleCake {}
pub struct OrangeCandleCake {}
pub struct MagentaCandleCake {}
pub struct LightBlueCandleCake {}
pub struct YellowCandleCake {}
pub struct LimeCandleCake {}
pub struct PinkCandleCake {}
pub struct GrayCandleCake {}
pub struct LightGrayCandleCake {}
pub struct CyanCandleCake {}
pub struct PurpleCandleCake {}
pub struct BlueCandleCake {}
pub struct BrownCandleCake {}
pub struct GreenCandleCake {}
pub struct RedCandleCake {}
pub struct BlackCandleCake {}
pub struct AmethystBlock {}
pub struct BuddingAmethyst {}
pub struct AmethystCluster {}
pub struct LargeAmethystBud {}
pub struct MediumAmethystBud {}
pub struct SmallAmethystBud {}
pub struct Tuff {}
pub struct Calcite {}
pub struct TintedGlass {}
pub struct PowderSnow {}
pub struct SculkSensor {}
pub struct OxidizedCopper {}
pub struct WeatheredCopper {}
pub struct ExposedCopper {}
pub struct CopperBlock {}
pub struct CopperOre {}
pub struct DeepslateCopperOre {}
pub struct OxidizedCutCopper {}
pub struct WeatheredCutCopper {}
pub struct ExposedCutCopper {}
pub struct CutCopper {}
pub struct OxidizedCutCopperStairs {}
pub struct WeatheredCutCopperStairs {}
pub struct ExposedCutCopperStairs {}
pub struct CutCopperStairs {}
pub struct OxidizedCutCopperSlab {}
pub struct WeatheredCutCopperSlab {}
pub struct ExposedCutCopperSlab {}
pub struct CutCopperSlab {}
pub struct WaxedCopperBlock {}
pub struct WaxedWeatheredCopper {}
pub struct WaxedExposedCopper {}
pub struct WaxedOxidizedCopper {}
pub struct WaxedOxidizedCutCopper {}
pub struct WaxedWeatheredCutCopper {}
pub struct WaxedExposedCutCopper {}
pub struct WaxedCutCopper {}
pub struct WaxedOxidizedCutCopperStairs {}
pub struct WaxedWeatheredCutCopperStairs {}
pub struct WaxedExposedCutCopperStairs {}
pub struct WaxedCutCopperStairs {}
pub struct WaxedOxidizedCutCopperSlab {}
pub struct WaxedWeatheredCutCopperSlab {}
pub struct WaxedExposedCutCopperSlab {}
pub struct WaxedCutCopperSlab {}
pub struct LightningRod {}
pub struct PointedDripstone {}
pub struct DripstoneBlock {}
pub struct CaveVines {}
pub struct CaveVinesPlant {}
pub struct SporeBlossom {}
pub struct Azalea {}
pub struct FloweringAzalea {}
pub struct MossCarpet {}
pub struct MossBlock {}
pub struct BigDripleaf {}
pub struct BigDripleafStem {}
pub struct SmallDripleaf {}
pub struct HangingRoots {}
pub struct RootedDirt {}
pub struct Deepslate {}
pub struct CobbledDeepslate {}
pub struct CobbledDeepslateStairs {}
pub struct CobbledDeepslateSlab {}
pub struct CobbledDeepslateWall {}
pub struct PolishedDeepslate {}
pub struct PolishedDeepslateStairs {}
pub struct PolishedDeepslateSlab {}
pub struct PolishedDeepslateWall {}
pub struct DeepslateTiles {}
pub struct DeepslateTileStairs {}
pub struct DeepslateTileSlab {}
pub struct DeepslateTileWall {}
pub struct DeepslateBricks {}
pub struct DeepslateBrickStairs {}
pub struct DeepslateBrickSlab {}
pub struct DeepslateBrickWall {}
pub struct ChiseledDeepslate {}
pub struct CrackedDeepslateBricks {}
pub struct CrackedDeepslateTiles {}
pub struct InfestedDeepslate {}
pub struct SmoothBasalt {}
pub struct RawIronBlock {}
pub struct RawCopperBlock {}
pub struct RawGoldBlock {}
pub struct PottedAzaleaBush {}
pub struct PottedFloweringAzaleaBush {}
